# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ContactWindow(object):
    def setupUi(self, ContactWindow):
        ContactWindow.setObjectName("ContactWindow")
        ContactWindow.resize(961, 707)
        ContactWindow.setStyleSheet("background-color: rgb(94, 92, 100);")
        self.centralwidget = QtWidgets.QWidget(ContactWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Back.setGeometry(QtCore.QRect(314, 638, 109, 37))
        self.pushButton_Back.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(2, -14, 305, 143))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ChatGPT Image Dec 8, 2025, 09_58_43 PM.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(534, 120, 385, 475))
        self.tableView.setStyleSheet("color: rgb(255, 255, 255);")
        self.tableView.setObjectName("tableView")
        self.pushButton_Send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Send.setGeometry(QtCore.QRect(168, 638, 109, 37))
        self.pushButton_Send.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);")
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(568, 40, 309, 43))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(24, 110, 77, 39))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.lineEdit_Topic = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Topic.setGeometry(QtCore.QRect(170, 120, 333, 26))
        self.lineEdit_Topic.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Topic.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_Topic.setObjectName("lineEdit_Topic")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(22, 174, 119, 39))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.plainTextEdit_Message = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_Message.setGeometry(QtCore.QRect(170, 172, 335, 423))
        self.plainTextEdit_Message.setStyleSheet("color: rgb(255, 255, 255);")
        self.plainTextEdit_Message.setObjectName("plainTextEdit_Message")
        ContactWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ContactWindow)
        self.statusbar.setObjectName("statusbar")
        ContactWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ContactWindow)
        QtCore.QMetaObject.connectSlotsByName(ContactWindow)

    def retranslateUi(self, ContactWindow):
        _translate = QtCore.QCoreApplication.translate
        ContactWindow.setWindowTitle(_translate("ContactWindow", "ContactWindow"))
        self.pushButton_Back.setText(_translate("ContactWindow", "Back"))
        self.pushButton_Send.setText(_translate("ContactWindow", "Send"))
        self.label_5.setText(_translate("ContactWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Previous Messages</span></p></body></html>"))
        self.label_6.setText(_translate("ContactWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Topic:</span></p></body></html>"))
        self.label_7.setText(_translate("ContactWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Your Message:</span></p></body></html>"))
import resources_rc
