# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 510)
        MainWindow.setStyleSheet("background-color: rgb(94, 92, 100);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Login.setGeometry(QtCore.QRect(116, 386, 91, 31))
        self.pushButton_Login.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);")
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(164, 28, 241, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ChatGPT Image Dec 8, 2025, 09_58_43 PM.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit_Login = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Login.setGeometry(QtCore.QRect(298, 196, 167, 26))
        self.lineEdit_Login.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(116, 190, 155, 39))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(298, 272, 167, 26))
        self.lineEdit_Password.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(114, 264, 155, 39))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.pushButton_Register = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Register.setGeometry(QtCore.QRect(234, 384, 97, 33))
        self.pushButton_Register.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);")
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.label_Msg = QtWidgets.QLabel(self.centralwidget)
        self.label_Msg.setGeometry(QtCore.QRect(114, 442, 359, 18))
        self.label_Msg.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_Msg.setText("")
        self.label_Msg.setObjectName("label_Msg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Login.setText(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Username or e-mail:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Password:</span></p></body></html>"))
        self.pushButton_Register.setText(_translate("MainWindow", "Register"))
import resources_rc
