# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(675, 733)
        RegisterWindow.setStyleSheet("background-color: rgb(94, 92, 100);")
        self.centralwidget = QtWidgets.QWidget(RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Create = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Create.setGeometry(QtCore.QRect(198, 604, 97, 33))
        self.pushButton_Create.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);")
        self.pushButton_Create.setObjectName("pushButton_Create")
        self.label_msg = QtWidgets.QLabel(self.centralwidget)
        self.label_msg.setGeometry(QtCore.QRect(200, 664, 359, 18))
        self.label_msg.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_msg.setText("")
        self.label_msg.setObjectName("label_msg")
        self.pushButton_Login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Login.setGeometry(QtCore.QRect(338, 604, 91, 31))
        self.pushButton_Login.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(94, 92, 100);")
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(222, 10, 241, 141))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/ChatGPT Image Dec 8, 2025, 09_58_43 PM.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(202, 438, 155, 39))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setScaledContents(False)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(202, 304, 155, 39))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setScaledContents(False)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(198, 510, 155, 39))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setScaledContents(False)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 370, 155, 39))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setScaledContents(False)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.lineEdit_Email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Email.setGeometry(QtCore.QRect(384, 376, 167, 26))
        self.lineEdit_Email.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.lineEdit_Username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Username.setGeometry(QtCore.QRect(384, 308, 167, 26))
        self.lineEdit_Username.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Username.setObjectName("lineEdit_Username")
        self.lineEdit_Password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Password.setGeometry(QtCore.QRect(384, 446, 167, 26))
        self.lineEdit_Password.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.lineEdit_Phone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Phone.setGeometry(QtCore.QRect(382, 514, 167, 26))
        self.lineEdit_Phone.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Phone.setObjectName("lineEdit_Phone")
        self.lineEdit_Lname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Lname.setGeometry(QtCore.QRect(386, 242, 167, 26))
        self.lineEdit_Lname.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Lname.setObjectName("lineEdit_Lname")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(202, 236, 155, 39))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setScaledContents(False)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.lineEdit_Fname = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Fname.setGeometry(QtCore.QRect(386, 174, 167, 26))
        self.lineEdit_Fname.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit_Fname.setObjectName("lineEdit_Fname")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(204, 170, 155, 39))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setScaledContents(False)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        RegisterWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RegisterWindow)
        self.statusbar.setObjectName("statusbar")
        RegisterWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Register Panel"))
        self.pushButton_Create.setText(_translate("RegisterWindow", "Create Account"))
        self.pushButton_Login.setText(_translate("RegisterWindow", "Login"))
        self.label_3.setText(_translate("RegisterWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Password:</span></p></body></html>"))
        self.label_2.setText(_translate("RegisterWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Username:</span></p></body></html>"))
        self.label_5.setText(_translate("RegisterWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Phone:</span></p></body></html>"))
        self.label_6.setText(_translate("RegisterWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">E-mail:</span></p></body></html>"))
        self.label_7.setText(_translate("RegisterWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Last Name:</span></p></body></html>"))
        self.label_4.setText(_translate("RegisterWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">First Name:</span></p></body></html>"))
import resources_rc
