# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 622)
        MainWindow.setStyleSheet("background-color: rgb(94, 92, 100);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 0, 151, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo.png/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tblOrders = QtWidgets.QTableView(self.centralwidget)
        self.tblOrders.setGeometry(QtCore.QRect(0, 100, 861, 341))
        self.tblOrders.setObjectName("tblOrders")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 450, 95, 103))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnTakeOrder = QtWidgets.QPushButton(self.layoutWidget)
        self.btnTakeOrder.setObjectName("btnTakeOrder")
        self.verticalLayout.addWidget(self.btnTakeOrder)
        self.btnDeliverOrder = QtWidgets.QPushButton(self.layoutWidget)
        self.btnDeliverOrder.setObjectName("btnDeliverOrder")
        self.verticalLayout.addWidget(self.btnDeliverOrder)
        self.btnRefresh = QtWidgets.QPushButton(self.layoutWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.verticalLayout.addWidget(self.btnRefresh)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTakeOrder.setText(_translate("MainWindow", "Sipariş al"))
        self.btnDeliverOrder.setText(_translate("MainWindow", "Teslim et"))
        self.btnRefresh.setText(_translate("MainWindow", "Güncelle"))
import resource_rc
